language: node_js
node_js:
  - node

before_script:
  - npm install
  - npm run build

script:
  - npm run lint
  - npm run test

after_success:
  - npm run format:fix
  - npm run typedoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
