language: node_js
node_js:
  - node

install:
  - npm install -g codecov

before_script:
  - npm install
  - npm run build
  - cd demo
  - npm install
  - cd ..

script:
  - npm run lint
  - npm run test:collect
  - codecov

after_success:
  - npm run docs:build

before_deploy:
  - touch docs/.vuepress/dist/.nojekyll

deploy:
  local_dir: docs/.vuepress/dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
